import BigNumber from 'bignumber.js'

export interface ContextValues {
  earnedBalanceVial?: BigNumber,
  isApprovedVial?: boolean,
  isApprovingVial?: boolean,
  isHarvestingVial?: boolean,
  isRedeemingVial?: boolean,
  isStakingVial?: boolean,
  isUnstakingVial?: boolean,
  onApproveVial: () => void,
  onHarvestVial: () => void,
  onRedeemVial: () => void,
  onStakeVial: (amount: string) => void,
  onUnstakeVial: (amount: string) => void,
  stakedBalanceVial?: BigNumber,
  earnedBalanceVamp?: BigNumber,
  isApprovedVamp?: boolean,
  isApprovingVamp?: boolean,
  isHarvestingVamp?: boolean,
  isRedeemingVamp?: boolean,
  isStakingVamp?: boolean,
  isUnstakingVamp?: boolean,
  onApproveVamp: () => void,
  onHarvestVamp: () => void,
  onRedeemVamp: () => void,
  onStakeVamp: (amount: string) => void,
  onUnstakeVamp: (amount: string) => void,
  stakedBalanceVamp?: BigNumber,
}